### ISSUE TITLE
Reduce boilerplate in CAPI2 files

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#257]
Currently we have a lot of small(ish) core files for our modules, all of which contain

```
targets:
  default:
    filesets:
      - files_rtl
```

Can we reduce the boilerplate a bit by using the following algorithm?

If no targets section or no targets.default section exists, one is automatically created with all filesets defined in this core file added to it.
