### ISSUE TITLE
Only set a vlogdefine, do not assign a value to it

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#263]
Goal: have fusesoc pass a define as "being set/defined" to a tool, do not assign a value to it.

Currently we have code like this:
```yaml
parameters:
  SYNTHESIS:
    datatype: str
    paramtype: vlogdefine

target:
  lint:
    parameters:
      - SYNTHESIS=1
```

Switching `SYNTHESIS=1` to `SYNTHESIS` will only make the vlogdefine available to the tool, but not set it. This is documented and intended behavior and generally makes sense.

For the "only define, don't assign a value" use case we need to extend the syntax a bit.

In the `target` section, I don't see a way to distinguish between "make vlogdefine available", "set vlogdefine without value", and "set vlogdefine to a given value".

I'd instead propose a new datatype `define` or `isset` or something like that (no good ideas come to mind right now). Assigning a truthy value (like 1 or true) to it would result in the define being set and passed to the EDA tool. Assigning a falsy value to it will not pass it to the EDA tool.
