### ISSUE TITLE
Warn or error if fileset includes files above core file

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#264]
We should warn or error out if users have a core file which specifies a file path in a fileset with a relative path above the core file, e.g.

```yaml
filesets:
   file_rtl:
     files:
      - ../other_module/something.sv
```

Using fusesoc like this can work (if other_module for some reason part of the build as well, e.g. because of a dependency), but it doesn't work in the general case.

We should warn loudly or error out if this behavior is detected.

Sounds good @olofk? I'll open a PR then.
