### ISSUE TITLE
Add support for use flags

### ISSUE THREAD

**Issue by olofk** [olofk/fusesoc#268]
Enable conditional expressions dependent on user-specified flags. Will use something similar to gentoo ebuild-style syntax. e.g xilinx ? (xilinx_memory.v) !xilinx (generic_memory.v)

Design considerations:

Ideally cores should be able to set requirements on use flags for their dependencies (local use flags), but this will require a new dependency manager as the current one isn't flexible enough. For that reason we will start with use flags set on the command-line that will affect every core in the dependency tree (global use flags). This way the flags will be evaulated before the satsolver starts

How should use flags be set?

* Command-specific switches e.g. `fusesoc run --target=sim --i_am_a_flag` ?
* A special flag switch e.g. `fusesoc run --target=sim --flags="+i_am_a_flag -this_flag_is_off" ?
* Something else?

How should flags be defined?

* A new flags section?
* As a new type of parameters?
* Skip this for now and just accept every flag set on the command line?

**Comment by amgibso** [comment]
I've started looking at the feasibility of using FuseSoC and this feature is very important. Due to cascading dependencies, one of our libraries that is most depended on has multiple implementations (VHDL architectures) for the entities. For example, use this architecture for Virtex4 or this architecture for StratixV. Currently we selectively include the required files but can't quite replicate that behavior using the existing implicit `tool_` or `target_` flags.

Command-line switches is certainly a very helpful start. Need to be able to distinguish them from other flags that can be passed in (e.g. `backendargs`, so something like this _may_ be suitable?
`fusesoc run --target=sim --flag="+i_am_a_flag" --flag="-this_flag_is_off"`
Each occurrence of `--flag` adds to a list which is easy to work through.

But in the long term in would be better to have this information in the project repository and not the IaC repository, so moving the information to the core file would make sense. I've only have a limited understanding of the underlying code, so don't have a full appreciation for how complicated this suggestion is, but would either of the following be feasible?

```
flags: # this is a new 'section' I've just made up
  family: virtex4
  vendor: xilinx

filesets:
  rtl:
    files:
      - ram.vhd # entity
      - "family_virtex4? (ram_virtex4.vhd)" # architecture

targets:
  default:
    filesets: [rtl]
```

or

```
flags: # this is a new 'section' I've just made up
  family: virtex4
  vendor: xilinx

filesets:
  rtl:
    files:
      - ram.vhd # entity

  rtlVirtex4:
    files:
      - ram_virtex4.vhd # architecture

targets:
  default:
    filesets: [rtl, "family_virtex4? (rtlVirtex4)"]
```
