### ISSUE TITLE
What about adding filesets_groups?

### ISSUE THREAD

**Issue by m-kru** [olofk/fusesoc#284]
Issue:
A lot of targets that share the same HDL sources but have different pinouts, synthesis and implementation strategies etc. 

Right now I repeat most of the filesets part for each target, like this:
```
 targets:
    target_0:
        default_tool: vivado
        tools:
            vivado:
                part: xc7a200tfbg484-2
        toplevel: my_top
        filesets:
            - target_0_pinout
            - target_0_settings
            - fileset_a
            - fileset_b
            .
            .
            .
            - fileset_z
  target_1:
        default_tool: vivado
        tools:
            vivado:
                part: xc7a200tfbg484-2
        toplevel: my_top
        filesets:
            - target_1_pinout
            - target_1_settings
            - fileset_a
            - fileset_b
            .
            .
            .
            - fileset_z

  target_N:
        default_tool: vivado
        tools:
            vivado:
                part: xc7a200tfbg484-2
        toplevel: my_top
        filesets:
            - target_N_pinout
            - target_N_settings
            - fileset_a
            - fileset_b
            .
            .
            .
            - fileset_z 
```
It leads to lots of repetitions and long .core files.
Imagine something like this:
```
filesets_groups:
  my_group:
     - fileset_a
     - fileset_b
     .
     .
     .
     - fileset_z    

 targets:
    target_0:
        default_tool: vivado
        tools:
            vivado:
                part: xc7a200tfbg484-2
        toplevel: my_top
        filesets:
            - target_0_pinout
            - target_0_settings
        filesets_groups:
            - my_group
  target_1:
        default_tool: vivado
        tools:
            vivado:
                part: xc7a200tfbg484-2
        toplevel: my_top
        filesets:
            - target_1_pinout
            - target_1_settings
        filesets_groups:
            - my_group

  target_N:
        default_tool: vivado
        tools:
            vivado:
                part: xc7a200tfbg484-2
        toplevel: my_top
        filesets:
            - target_N_pinout
            - target_N_settings
        filesets_groups:
            - my_group
```

Such construct is shorter and easier to manage. What do you think?
If any mechanism similar to this already exists let me know, and forgive me, but I was not able to find it in any example or documentation.
