### ISSUE TITLE
CAPI2 file types

### ISSUE THREAD

**Issue by djcopley** [olofk/fusesoc#292]
~~I have not been able to find one go-to place for file_type parameters. I have read the documentation and done a bit of digging through the source code, and have yet to find a comprehensive list of these identifiers. To make things more confusing, some of the information I have found seems to be incorrect? The following snippet in the edalize vivado backend:~~

```
Vivado Backend
A core (usually the system core) can add the following files:
- Standard design sources
- Constraints: Supply xdc files with file_type=xdc
- IP: Supply the IP core xci file with file_type=xci and other files (like .prj)
      as file_type=data
```

~~File type xdc, xci, and data yield `unknown file type '[xdc, xci, data]'`(the brackets indicate a selection of one of the three, not all three). I am aware that this information applies to the edalize package; however, I assume that fusesoc passes these parameters to the backend.~~

*Fixed*
~~On a separate note, I am having trouble getting the pnr option working. I have installed the latest version of fusesoc and edalize using pip, to no avail. While it is likely user error, any suggestions are appreciated. My target:~~

```
targets:
  synth:
    default_tool: vivado
    filesets: [src]
    tools:
      vivado:
        part: xc7a200tfbg676-2
        pnr: none
    toplevel: topblock
```

For context, I am trying to package a xilinx bist using fusesoc.
