### ISSUE TITLE
Supporting dependency ranges in CAPI file filesets

### ISSUE THREAD

**Issue by GCHQDeveloper992** [olofk/fusesoc#315]
I was thinking it might be beneficial to support a dependency range in CAPI files to cut down on repetitive typing. For example, I have a number of cores that are semantically versioned so I often want to include the range of versions between one major release and the next, e.g.

```yaml
CAPI=2:
name: somevendor:somelibrary:somecore:1.0.0

filesets:
  rtl:
    depend:
      - ">=somevendor:somelibrary:anothercore:1.0.0"
      - "<somevendor:somelibrary:anothercore:2.0.0"
     ....more capi file....
```

For some cores that have lots of dependencies, this gets quite repetitive. I was wondering if the following syntax might be nicer:

```yaml
filesets:
  rtl:
    depend:
      - ">=<somevendor:somelibrary:anothercore:1.0.0/2.0.0"
     ....more capi file....
```

I believe with a small modification to coremanager.py _parse_depend function we could identify the new >=< relation operator, and automatically append two strings to the deps array - one for the >= relation for the 1.0.0 version before the '/' and another for the < relation for the 2.0.0 after the slash.

I could try and put together a quick demo branch of this behaviour to see if that's all that would be involved.

Does that sound like a useful feature for more than just me? Or have I missed a capability that already exists?
