### ISSUE TITLE
Hook scripts are called from wrong directory when part of a fileset

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#353]
Have a look at this core file defining a hook and an associated fileset.

```
CAPI=2:
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
name: "lowrisc:ibex:check_tool_requirements:0.1"
description: "Check tool requirements"

filesets:
  files_check_tool_requirements:
    files:
      - ./util/check_tool_requirements.py
      - ./tool_requirements.py

scripts:
  check_tool_requirements:
    cmd: 
      - python3 
      - util/check_tool_requirements.py
    filesets:
      - files_check_tool_requirements

targets:
  default:
    hooks:
      pre_build:
        - tool_verilator ? (check_tool_requirements)
```

When executing, we get the following:

```
DEBUG: Working directory: /home/philipp/src/ibex/build/lowrisc_ibex_ibex_core_tracing_0.1/lint-verilator
python3: can't open file 'util/check_tool_requirements.py': [Errno 2] No such file or directory
```

The problem:
- The working directory is `build/lowrisc_ibex_ibex_core_tracing_0.1/lint-verilator`
- The script is copied to `build/lowrisc_ibex_ibex_core_tracing_0.1/lint-verilator/../src/lowrisc_ibex_check_tool_requirements_0.1/`

Things are made worse by the fact that `copyto` on filesets included as part of a script are ignored.

@olofk has this ever been working, and if so, how? Or how would you expect this to work?
