### ISSUE TITLE
Bool parameters which default to enabled can't be disabled

### ISSUE THREAD

**Issue by rswarbrick** [olofk/fusesoc#392]
If a core file specifies a boolean parameter like this (taken from Ibex):
```
  RV32M:
    datatype: bool
    paramtype: vlogparam
    default: true
    description: Enable the M ISA extension (hardware multiply/divide)
```
then the argument parser for `fusesoc run` gets a `--RV32M` argument which takes no arguments and switches the flag on. This is very clean and nice!

Of course, the example above has `default: true`, so passing `--RV32M` has no effect. However, there's no `--no-RV32M` flag to turn the feature off. Oh no!
