### ISSUE TITLE
Parameters from upper level core file

### ISSUE THREAD

**Issue by wallento** [olofk/fusesoc#401]
When an IP block defines a parameter, in particular `vlogdefine`, it should be possible to set it from the target block of the toplevel design.
For example an IP block can define:
```yaml
  parameters:
    MYDEFINE:
      datatype: int
      paramtype: vlogdefine
      default: 8
```
The toplevel should be able to set this via its targets section:
```yaml
  targets:
    synth:
      parameters:
        - MYDEFINE=2
```
This currently does not work, error:

```
ERROR: Parameter 'MYDEFINE', requested by target 'synth', was not found
```
The workaround is to add a duplicate for this parameter in the parameters section:
```yaml
parameters:
  MYDEFINE:
    datatype: int
    paramtype: vlogdefine
```

It should be allowed to do this without this workaround.
