### ISSUE TITLE
Running two targets for the same core simultaneously without `--no-exports` results with error.

### ISSUE THREAD

**Issue by m-kru** [olofk/fusesoc#425]
This behavior results from 2 facts:

1. When sources are exported, they are copied to the `src/` directory which is located in the `build/core/` directory, not in the `build/core/target/` directory.
2. On the new export for the same core, but different target, the `src/` directory is removed (`capi2/core.py` file).
```python
    def export(self, dst_dir, flags={}):
        if os.path.exists(dst_dir):
            shutil.rmtree(dst_dir)
``` 
Sources which are included in the first target, but are not included in the second one, will be removed and run for the first target will fail. This makes it impossible to run some verification targets in parallel.

One can say, "so lets run them with `--no-export` flag". However, some verification targets may take significant time, and in the meantime user may want to continue working. 

I would like to make the `src/` directory, with copied sources, to be bound to a target, not a core.
Does anyone see any potential problems?

**Comment by ThomasHornschuh** [comment]
Why not get a step further and have an option to run FuseSoC on a temporary target directory with a unique name for every run?
This would give the option to run several configurations (e.g. different parameters) of the same target in parallel.  
A common case would be a CPU test suite, where you usually run a lot of small test programs in the CPU core. 

I tried this a while ago with RISC-V compliance and was already thinking about such a feature for FuseSoC, but then postponed the idea because the makefiles in the compliance suite itself are not built in a way to support parallel runs with using the -j option of make.

**Comment by imphil** [comment]
@m-kru I need to think about that a bit more, but I see your point.

In the mean time, the easiest solution is to use `--build-root /some/unique/directory` (such as `--build-root "$(mktemp -d)"`)

**Comment by m-kru** [comment]
@ThomasHornschuh I think I do not understand which configurations you have in mind. In case of `.core` file you define parameters per target, so each target already has distinct configuration. Example snippet:
```yaml
targets:
  base_target: &base
    default_tool: vivado
    tools:
      vivado:
        part: xc7k325tffg900-2
    filesets:
     - vivado_project_settings
     - common

  shuffler_sequential_3_muxes:
    <<: *base
    toplevel: top_shuffler_sequential
    filesets_append:
      - top_shuffler_sequential
    parameters : [G_NUM_MUXES=3]

  shuffler_sequential_4_muxes:
    <<: *base
    toplevel: top_shuffler_sequential
    filesets_append:
      - top_shuffler_sequential
    parameters : [G_NUM_MUXES=4]

  shuffler_sequential_5_muxes:
    <<: *base
    toplevel: top_shuffler_sequential
    filesets_append:
      - top_shuffler_sequential
    parameters : [G_NUM_MUXES=5]

parameters:
  G_NUM_MUXES:
    datatype : int
    description : Number of internal muxes in sequential shuffler.
    paramtype : generic

```
