### ISSUE TITLE
Generating Board Specific IPs

### ISSUE THREAD

**Issue by hossein1387** [olofk/fusesoc#505]
In my design, I am using Xilinx BRAM IPs that were generated for a specific FPGA board. In my core file, in the synthesis part, I am referencing this IP as below:

```
filesets:
    rtl:
           - ...
    synth:
        file_type : systemVerilogSource
        files:
           - rtl
            - ip/xilinx/bram_32Kb.xci:
                file_type: xci
    xdc:
        files:
            - synthesis/constraint_files/pito_core.xdc
        file_type: xdc

    synth:
        filesets:
            - synth
            - xdc
        default_tool: vivado
        tools:
          vivado:
            part: xcku040-fbva676-2-e
        toplevel: [rv32_core]
```

The `bram_32Kb.xci` was specifically generated for `xcku040-fbva676-2-e` FPGA. I want to test my design on different FPGAs. Is there a way in fusesoc to generate IPs depending on the part number?
