### ISSUE TITLE
Pass parameters/generics to scripts

### ISSUE THREAD

**Issue by faberc** [olofk/fusesoc#514]
I think the feature for parameters to be able to be passed to scripts would be incredibly useful.

For example:
```
scripts:  
  gen-ocf:
    cmd: [python, ocf-gen.py, $(dataLength), $(outgoingBytes), $(EnableTrailer), $(ErrorRate)]
    filesets:
      - misc
```

Where everything wrapped in "$(" ")" is checked against the list of parameters in the core file as a whole or for a specified target and if it exists, these arguments are replaced with the current active value for that parameter (specified by priority: (1) passed as runtime flag, (2) target default, (3) global default) when they are run.

This is functionality that would be needed for any scripts that depend on parameters and generics to generate appropriate test vectors, etc.
