### ISSUE TITLE
Unknown item 'Integer'. Parse Error

### ISSUE THREAD

**Issue by alperyazar** [olofk/fusesoc#515]
Hi,

I am using FuseSoC with Vivado.  When I define a parameter with `Integer` type like `jtag_freq` or `jobs`, FuseSoC throws this error. Other `String` type settings like `part` works fine.  Is it a problem related to CAPI2 parser, `fusesoc/capi2/core.py` ? It looks like parser doesn't know `Integer` type settings. FuseSoC 1.12.0 is installed with edalize 0.2.5. Problem exists both on Windows and Linux.

A question: Is it possible to override `jobs` parameter of Vivado (or any parameter in general) from command line when calling FuseSoC. I want to set this parameter on Linux with `$nproc` while calling the FuseSoC like `make -j$(nproc)`.

Thanks

**Comment by imphil** [comment]
Thanks for your report. Can you show us a full core file that reproduces the problem?

**Comment by alperyazar** [comment]
Thanks for the response. Here is the MWE.

`fusesoc.core`:

```yaml
CAPI=2:

name: a:b:c:0-r0

filesets:
  rtlverilog:
    files:
      - top.v
    file_type: verilogSource

targets:
  default:
    filesets : [rtlverilog]
  prj:
    default_tool: vivado
    filesets: [rtlverilog]
    toplevel : top
    tools:
      vivado:
        part: abc
#        jobs: 8
#        jtag_freq: 1
```

At the same level, created a dummy `top.v`. Then I run:

```bash
fusesoc library add test ./
```

then

```bash
fusesoc run --target prj --setup a:b:c
```

Everything works fine if `jobs` or `jtag_freq` is commented. When I uncomment at least one of them I get the error:

```text
WARNING: Parse error. Ignoring file xxx\fusesoc.core: Unkown item 'Integer'
```

Here is the installed packages with `pipdeptree -p fusesoc`

```text
$ pipdeptree -p fusesoc
fusesoc==1.12.0
  - edalize [required: >=0.2.3, installed: 0.2.5]
    - Jinja2 [required: >=2.11.3, installed: 2.11.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
  - ipyxact [required: >=0.2.3, installed: 0.2.4]
    - pyyaml [required: Any, installed: 5.4.1]
  - pyparsing [required: Any, installed: 2.4.7]
  - pyyaml [required: Any, installed: 5.4.1]
  - simplesat [required: >=0.8.0, installed: 0.8.2]
    - attrs [required: >=17.4.0, installed: 20.3.0]
    - okonomiyaki [required: >=0.16.6, installed: 1.3.0]
      - attrs [required: >=16.1.0, installed: 20.3.0]
      - jsonschema [required: >=2.5.1, installed: 3.2.0]
        - attrs [required: >=17.4.0, installed: 20.3.0]
        - pyrsistent [required: >=0.14.0, installed: 0.17.3]
        - setuptools [required: Any, installed: 49.2.1]
        - six [required: >=1.11.0, installed: 1.15.0]
      - six [required: >=1.9.0, installed: 1.15.0]
      - zipfile2 [required: >=0.0.12, installed: 0.0.12]
    - six [required: >=1.10.0, installed: 1.15.0]
```

Result is the same on both Windows and Linux. May be a incompatibility with latest version of `pyyaml` or `pyparsing`?
