### ISSUE TITLE
Pass parameters/generics as variables in CORE file.

### ISSUE THREAD

**Issue by faberc** [olofk/fusesoc#519]
I accidentally closed the other issue when I didn't mean to...

The idea was to allow parameters to be passed to hook scripts by defining them in the fusesoc core file.

For example:
```
scripts:
  gen:
    cmd: [python, bench.py, $(VAR)]
    filesets:
      - misc

parameters:
  VAR:
    datatype: int
    default: 9
    description: Random Variable 
    paramtype: generic
```
Depending on the latest definition of the VAR parameter, (either the global default, the target default, or overridden with a command line argument), $(VAR) would be replaced with the correct value.

I think this replacement could be done in the Edalizer class, since it automatically finds the most up to date value of these parameters.

But it also should be able to replace variables if they exist in core file parameter list even if it isn't explicitly set in the target I think (if the parameter is just a global default).

A new method might be created in the Edalizer class in edalizer.py that takes the edalizer dictionary, converts it to a string then does a string replace for the variable syntax with the default value found for the parameter.

```
def replaceVariables(self):
	eda_str = json.dumps(self.edalizer)
	top_core = self.resolved_cores[-1]
	global_params = top_core.get_parameters()
	for key in global_params.keys():
		if key in self.edalizer["parameters"]:
			_param = self.edalizer["parameters"][key]
		else:
			_param = global_params[key]
		eda_str = eda_str.replace("$("+key+")", _param["default"]
self.edalizer = json.loads(eda_str)
```

Then this method could be called after the `edalizer.add_parsed_args()` line in main.py.

Let me know what you think about this feature.
