### ISSUE TITLE
parameter datatype file: missing path prefix

### ISSUE THREAD

**Issue by nopeslide** [olofk/fusesoc#529]
According to the [parameter CAPI2 reference](https://fusesoc.readthedocs.io/en/stable/ref/capi2.html#parameter) the value of a `file` datatype should be prefixed with the path fusesoc in which was started.
I have a firmware file that needs to be loaded on simulation start:
```yaml
...
targets:
  ...
  jump_loop_tb:
    ...
    parameters:
      - g_FILE_PATH=firmware/jump_loop.mem

parameters:
  g_FILE_PATH:
    datatype: file
    description: Firmware file to load
    paramtype: generic
```
but in the resulting `*.eda.yml` files it is not prefixed:
```yaml
