### ISSUE TITLE
How to use dependencies from non-default target

### ISSUE THREAD

**Issue by mballance** [olofk/fusesoc#531]
I'm working with some .core files that deal with fairly different collections of source that cannot be processed together by the same tool (think Verilog and documentation source). Cores have dependency chains >1 in depth.
My hope was to use different 'targets' to organize the dependent filesets:

Dep_1_1:
```
filesets:
  rtl:
    # ...
  rst:
    # ...

targets:
  hdl:
    filesets:
      - rtl
  doc:
    filesets:
      - rst
```
Dep_1:
```
filesets:
  rtl:
    # ...
    depend:
      - Dep_1_1
  rst:
    # ...
    depend:
      - Dep_1_1

targets:
  hdl:
    filesets:
      - rtl
  doc:
    filesets:
      - rst
```

TopLevel:
```
filesets:
  rtl:
    # ...
    depend:
      - Dep_1
  rst:
    # ...
    depend:
      - Dep_1

targets:
  hdl:
    filesets:
      - rtl
  doc:
    filesets:
      - rst
```

My expectation was that when I processed `Toplevel` and target `doc`, I would receive the .rst files from `Toplevel`, `Dep_1`, and `Dep_1_1`. What I find is that I actually receive just the files from `Toplevel` and `Dep_1`. 

My understanding is that the following logic prevents the target `doc` from being evaluated for Dep_1_1 because we are not processing the dependencies for a top-level core:
https://github.com/olofk/fusesoc/blob/b05eed5b68e819d219ac9a3fc959bf1fe740ff91/fusesoc/capi2/core.py#L631-L644

I have confirmed that if I add a 'default' target to `Dep_1_1`, those files are brought along as dependencies.

Is there a way to cause evaluation of a named (non-default) target for dependencies of non-toplevel cores? Is restricting dependencies to the default target for dependencies of non-toplevel cores a key assumption of FuseSoc? In other words, would something bad happen if this were supported?

Thanks for your time in reading through all of this!
-Matthew

**Comment by sjalloq** [comment]
I don't know the reasoning behind it, but yes, by design only the default target is used for dependencies.

You have two options to work around this, use target based flags or just have separate core files for the two targets.

```yaml
targets:
  default:
    filesets:
      - target_doc ? (rst)
      - target_hdl ? (rtl)
```
