### ISSUE TITLE
vhdl generics parameters not working with Xsim on windows

### ISSUE THREAD

**Issue by Steinegger** [olofk/fusesoc#543]
I've encountered and issue with the fusesoc vhdl parameters/generics on windows when using xsim. I added a paramters section to my .core file and also referenced this parameter in the simulation target:
```
parameters:
  MY_PARAM:
    datatype: int
    default: 60
    description: "something"
    paramtype: generic
```

If I run the fusesoc command this will result in
`ERROR: [XSIM 43-3225] Cannot find design unit work.60 in library work located at xsim.dir/work.`

The culprit seems to be the way the parameters are generated in the resulting makefile:
```
GEN_PARAMS = --generic_top MY_PARAM=60
```

If I change this to 
```
GEN_PARAMS = --generic_top "MY_PARAM=60"
```
and call the makefile manually with `make run-gui` or `make run` it works as intended.

Fusesoc: 1.12.0
Edalize: 0.3.3
