### ISSUE TITLE
vunit target is not working

### ISSUE THREAD

**Issue by oholimoli** [olofk/fusesoc#544]
When I use the target "vunit" in a fusesoc core, it is not possible to run the tests directly because I get an error:

```
bash-4.4$ fusesoc run --target=test ci_test
INFO: Preparing ::ci_test:0
INFO: Setting up project

INFO: Running pre_build script hello_1
/usr/bin/python3: can't open file './build/ci_test_0/test-vunit/run.py': [Errno 2] No such file or directory
ERROR: Failed to build ::ci_test:0 : '['/usr/bin/python3', './build/ci_test_0/test-vunit/run.py', '--compile', '-k']' exited with an error: 2
```

The file `run.py` is created correctly, this seems to be a path problem. This works:

```
bash-4.4$ fusesoc run --setup --target=test ci_test
INFO: Preparing ::ci_test:0
INFO: Setting up project

OK
```

After I run one of the commands above I can run VUnit this way:
```

bash-4.4$ fusesoc run --setup --target=test ci_test
bash-4.4$ cd build/ci_test_0/test-vunit/
bash-4.4$ python3 run.py
/usr/local/lib/python3.6/site-packages/vunit/builtins.py:103: Warning: 'array_t' is deprecated and it will removed in future releases; use 'integer_array_t' instead
  warn(arr_deprecation_note, Warning)
```

This is my core file:

```
CAPI=2:

name: ::ci_test
description: Test the CI

filesets:

  test:
    files:
      - test/tb_test.vhd
    file_type: vhdlSource

targets:
  default: &default
    filesets:
      - test

  test:
    <<: *default
    default_tool: vunit
    description: Run tests with VUnit
    filesets:
      - test
    toplevel: tb_test

```

and this is the test bench:

```
library vunit_lib;
context vunit_lib.vunit_context;

entity tb_test is
  generic (runner_cfg : string);
end entity;

architecture tb of tb_test is
begin
  main : process
  begin
    test_runner_setup(runner, runner_cfg);
    while test_suite loop

        if run("testcase_1") then
            report "Hello from testcase_1";
        elsif run("testcase_2") then
            report "Hello from testcase_2";
        end if;
      end loop;
    test_runner_cleanup(runner);
  end process;
end architecture;
```
