### ISSUE TITLE
Add support for depend in generate.

### ISSUE THREAD

**Issue by m-kru** [olofk/fusesoc#558]
To bring in the core with generator one needs to artificially add fileset like this:

```yaml
filesets:
  agwb_dep:
    depend:
      - wzab::addr_gen_wb

generate:
  smx_tester:
    generator: addr_gen_wb
    parameters:
      infile: ../top_3_feb_c.xml

targets:
  default:
    generate:
      - smx_tester
    filesets:
      - agwb_dep
```

It would be really nice to be able to specify depend within the generate, like this:

```yaml
generate:
  smx_tester:
    depend: [wzab::addr_gen_wb]
    generator: addr_gen_wb
    parameters:
      infile: ../top_3_feb_c.xml

targets:
  default:
    generate:
      - smx_tester
```
