### ISSUE TITLE
Incorrect dependancy pulling

### ISSUE THREAD

**Issue by GCHQDeveloper211** [olofk/fusesoc#565]
With these example core files:
[osvvm.zip](https://github.com/olofk/fusesoc/files/8541246/osvvm.zip)

It seems if you for example try to set your dependancy to be >= 2020.05, only 2021.10 will be pulled.
(and not 2022.01 or 2022.02) Although if you change the version of the core file to be 2022.11 or anything such that the second minor number is greater than 10. It will assume that that core file is the next highest. I can see that it can see the higher versioned core files as if I say ==2022.01 it will pull from it directly.

**Comment by imphil** [comment]
Thanks for your report. I'm not quite sure I fully understand your problem. Can you show the core file in which you specify the dependency to osvvvm? And by "pulling", you mean the dependency is wrong, or the git provider is doing something wrong?

**Comment by GCHQDeveloper211** [comment]
Sorry. The dependancy is wrong.
So our core file that depends on OSVVM is as follows:
```
CAPI=2:

name: :fpga-cores:tb-helpers:0.0.0

filesets:
  rtl:
    depend:
      - ">=::osvvm:2020.05"
    files:
      - source/packages/tb_helpers.vhd
    file_type: vhdlSource-2008
    logical_name: fpga_cores

  test:
    depend:
      - ">=::osvvm:2020.05"
    files:
      - source/test/test_tb_helpers.vhd
    file_type: vhdlSource-2008
    logical_name: fpga_cores

targets:
  default:
    filesets: [rtl]

  sim:
    default_tool: modelsim
    filesets: [rtl, test]
    toplevel:
      - fpga_cores.test_tb_helpers
```

And when running a fuses run --target sim. This will use the osvvm core 2021.10, as opposed to the expected 2022.02

**Comment by imphil** [comment]
Given your constraint (">=::osvvm:2020.05"),  2021.10 is a valid choice,  isn't it? I think we had some confusion there in the past, are you expecting the newest available core to be used if multiple are valid solutions?

**Comment by GCHQDeveloper211** [comment]
I am expecting the newest core to be used, which would be 2022.02. Is that not the expected behaviour?

**Comment by GCHQDeveloper211** [comment]
Equally if I say (">=::osvvm:2022.01") it will still use 2021.10 as its dependancy.

**Comment by GCHQDeveloper963** [comment]
This behaviour is not due to anything that fusesoc is doing, but is instead caused by a dependency of simplesat, okonomiyaki, and is the expected behaviour within okonomiyaki. We can work around it by making a modification to our core files.

The issue is that the OSVVM version numbers can have a leading zero in the month field (i.e. "2022.01"); okonomiyaki treats leading zeroes as being invalid, [raising an error](https://github.com/enthought/okonomiyaki/blob/51b8b4fa8d17255e13c097402691726545cf5b4c/okonomiyaki/versions/pep386.py#L156-L157). If this error is raised then the version is marked as [worked around](https://github.com/enthought/okonomiyaki/blob/.51b8b4fa8d17255e13c097402691726545cf5b4c/okonomiyaki/versions/pep386_workaround.py#L21-L23). Then in the actual comparison, if both of the versions being compared are worked around then the `__le__` method attempts a comparison. If `self` is marked as worked around and the other is not then the method always returns `True`, otherwise `False` is always returned. Okonomiyaki [actively discourages](https://github.com/enthought/okonomiyaki/blob/51b8b4fa8d17255e13c097402691726545cf5b4c/okonomiyaki/versions/pep386.py#L76-L87) the use of years as version numbers, which is why leading zeroes are considered invalid.

I have put together some examples to help demonstrate this.

Where `other` is marked as worked around, `False` is returned

```python
from okonomiyaki.versions import EnpkgVersion
ev1 = EnpkgVersion.from_string("2021.11-0")
ev2 = EnpkgVersion.from_string("2022.03-0")
print(ev1 < ev2)  # prints False
```

Where `self` is marked as worked around, `True` is returned

```python
ev1 = EnpkgVersion.from_string("2021.01-0")
ev2 = EnpkgVersion.from_string("2022.13-0")
print(ev1 < ev2)  # prints True
ev2 = EnpkgVersion.from_string("2020.1-0")
print(ev1 < ev2)  # prints True
```

Where both `self` and `other` are marked as worked around, the parts of the version number that are not zero prefixed are compared.

```python
ev1 = EnpkgVersion.from_string("2021.01-0")
ev2 = EnpkgVersion.from_string("2022.01-0")
print(ev1 < ev2)  # prints True
ev2 = EnpkgVersion.from_string("2020.01-0")
print(ev1 < ev2)  # prints False
```

We can work around this within our OSVVM core file by changing the core name to not have a leading zero on the month portion of the version number, e.g.

```yaml
CAPI=2:

name: ::osvvm:2020.1
# ...
provider:
  name: git
  repo: https://github.com/OSVVM/OSVVM
  version: 2020.01
```
