### ISSUE TITLE
Propagate tools options from a dependency core

### ISSUE THREAD

**Issue by mkchri** [olofk/fusesoc#578]
is it possible to propagate the tools options from a dependency core to top level core? I am using a Cadence VIP it is using some runtime flag specific to Xcelium and I've ported those as "xrun_options" under tools options:

```
targets:
  default: &default_target
    filesets:
      - sv_files
      
  sim:
    <<: *default_target
    default_tool: xcelium
    tools:
      xcelium:
        xrun_options:
          - -sv_lib libcdnvipcuvm.so
          - -loadvpi /tools/eda/cadence/vipcat/11.30.081/tools.lnx86/denali_64bit/verilog/libcdnsv.so:cdnsvVIP:export
          - -cdn_vip_root /tools/eda/cadence/vipcat/11.30.081 -cdn_viplib -cdn_vip_svlib
```

Currently I have to copy the tools option to any top level core file that use this VIP as dependencies.  wondering if there is a better way to avoid this.
