### ISSUE TITLE
parameters_append overwrite inherited parameters_append

### ISSUE THREAD

**Issue by hipolitoguzman** [olofk/fusesoc#624]
Hi! First of all, thanks for this awesome tool! It's reducing a lot of friction in my day-to day development, and being able to finally have a sane way of setting up continuous integration is priceless :D

I'm having an issue that I'm not sure if it's the expected behavior. When I use ``parameters_append`` more than once, the previous inherited ``parameters_append`` properties get overwritten by the last one.

In the MWE below, target ``default`` defines ``PARAM1`` (with ``parameters``), target ``child`` (which inherits from ``default``) defines ``PARAM2`` (with ``parameters_append``)  and target ``grandchild`` (which inherits from ``child``) defines ``PARAM3`` (with ``parameters_append``). When setting up target ``grandchild``, ``PARAM2`` doesn't appear in the generated tcl scripts.

Since using ``parameters`` in a target would already override all inherited parameters, I would expect ``parameters_append`` to allow appending a number of parameters among different inheritance steps.

I suppose the overwriting is happening at the YAML level, nevertheless it would be nice to have a way of having multiple ``parameters_append``, to avoid having duplicated constants.

## How to reproduce

1. Copy the following YAML code into a file named ``test_parameters_append.core``

```YAML
CAPI=2:                                                                         
name: ::test_parameters_append:0.1                                              
description: Testing whether a second parameters_append overwrites the first one
                                                                                
targets:                                                                        
  default: &default                                                             
    description: default target, includes "parameters" property                 
    default_tool: ise                                                           
    toplevel: this_entity_doesnt_exist                                          
    parameters: [PARAM1=1]                                                      
                                                                                
  child: &child                                                                 
    <<: *default                                                                
    description: inherits from default, has "parameters_append" property        
    tools:                                                                      
      ise:                                                                      
       family: Spartan6                                                         
       device: xc6slx9                                                          
       package: csg324                                                          
       speed: -2                                                                
    parameters_append: [PARAM2=2]                                               
                                                                                
  grandchild:                                                                   
    <<: *child                                                                  
    description: inherits from child, has "parameters_append" property          
    parameters_append: [PARAM3=3]                                               
                                                                                
parameters:                                                                     
  PARAM1:                                                                       
    datatype    : int                                                           
    description : First parameter                                               
    paramtype   : generic                                                       
  PARAM2:                                                                       
    datatype    : int                                                           
    description : Second parameter                                              
    paramtype   : generic                                                       
  PARAM3:                                                                       
    datatype    : int                                                           
    description : Third parameter                                               
    paramtype   : generic              
```

2. Have Xilinx ISE in your ``$PATH`` (the issue also happens with Vivado, so Vivado could also be used)

3. Run the command ``fusesoc --verbose --cores-root . run --setup --target=grandchild ::test_parameters_append:0.1``

## What I expected to happen

I expected the generated  tcl file at ``build/test_parameters_append_0.1/grandchild-ise/test_parameters_append_0.1.tcl`` to contain the following line:

```tcl
project set "Generics, Parameters" "PARAM1=1|PARAM2=2|PARAM3=3" -process "Synthesize - XST"
```
## What actually happened

Actually, ``PARAM2`` is missing from the generated tcl file:

```tcl
project set "Generics, Parameters" "PARAM1=1|PARAM3=3" -process "Synthesize - XST"
```
