### ISSUE TITLE
Add syntax to map parameter to a specific toplevel

### ISSUE THREAD

**Issue by olofk** [olofk/fusesoc#667]
When using multiple top levels, which sometimes is the case for simulations, there is currently no way to tell the EDA tools which toplevel that should use a specific parameter. Unfortunately, it seems like some EDA tools get angry when they receive parameters that they don't know about.

One idea could be to have an optional dot notation for the parameters key in the target section, e.g.
```yaml
targets:
  sim:
    ...
    parameters: [some_param, specific_top.another_param]
```

which would send `some_param` to all toplevels but only send `another_param` to the `specific_top` toplevel
