### ISSUE TITLE
Modelsim with Cocotb

### ISSUE THREAD

**Issue by sebinho** [olofk/fusesoc#676]
Hi @olofk,

I have been successfully using fusesoc with Modelsim and cocotb for a while now. 
I wanted to update my core files to reflect the latest changes in edalize for cocotb support. But it does not seem to work with Modelsim.
Here is my example core file.

```yaml
CAPI=2:
name: test:i2c:0
description: test lib for I2C

filesets:
    vhdl_files:
        files:
            - hdl/i2c_slave.vhd
        file_type: vhdlSource-2008

    sim:
        files:
            - sim/i2c_slave_tb.py:              {file_type : user, copyto : .}

targets:

    sim:
        filesets: [vhdl_files, sim]
        toplevel: i2c_slave
        flow: sim
        flow_options:
            tool: modelsim
            cocotb_module: i2c_slave_tb
```

I get the following error on the command line:

```bash
> fusesoc run --target=sim vx:i2c:0:0
INFO: Preparing test:i2c:0:0
ERROR: Setup failed : Could not find tool 'modelsim'
```

Do you know what I am doing wrong?
Thanks for your help
