### ISSUE TITLE
Question: `env` section problem.

### ISSUE THREAD

**Issue by BaseHardware** [olofk/fusesoc#679]
Hello, I am a newbie of fusesoc.
I declared the script entries in my core file and added an `env` section to the entries to designate some environmental variables when executing commands in the script entry.
The entries in the `scripts` section of my core file will be used in the `pre_build` or `post_build` section of the `synth` target.

However, I cannot see any environment variables declared in my core file. How can could it be? Am I wrong in writing the core file?
The following codelet is a part of my core file:

```
targets:
  default: &default
    filesets:
      - test_files
    hooks:
      pre_build:
        - testscr


scripts:
  testscr:
    cmd:
      - "@python3 ./print_environ.py"
    env:
      test: testvar
```

`print_environ.py` does not show the environmental variable of `test`.
Is this an intended behavior? How can I put an environment variable to my script?
