### ISSUE TITLE
What is the file_type for SDF file

### ISSUE THREAD

**Issue by desorya** [olofk/fusesoc#697]
Hi there,

I'm trying to run gate-level simulation with existed netlist on VCS so that I need to involve a standard delay file.
I build a fileset like below but I don't know the exact file type for it.
```
filesets:
  sdf:
    files:
      - single_macro/env/MLM_macro_top_A.func_ssg_Cworst_T_m40.sdf.gz
```
I tried `sdf`, `sdfSource`, `standardDelayFile` and `DELAYFILE` but nothing worked. The sdf file still not shown on generated file list.

Thank you!
