### ISSUE TITLE
Problem with provider version of a core and fuesoc cache 

### ISSUE THREAD

**Issue by ohofherr** [olofk/fusesoc#700]
We found a problem regarding the field `version` in the section `provider` of a core and the fusesoc cache folder.

When the value in the field `version` is changed from `v1.0.4-rc0` to `v1.0.4-rc1` for example, fusesoc doesn't notice this and the files are not updated in the cache folder. The only workaround ist to change the version in the core `name: :some:core:1.0.4` => `name: :some:core:1.0.5` which is not possible, because the core is used as a dependency of another core and an update of the version number of the core would cause a domino effect.

We have a single repo for all our cores and the cleanest solution to this problem would be if fusesoc checks also the version in the provider section.

I think this issue should be classified as a bug.

```
CAPI=2:

name: :some:core:1.0.4
description: Some core

filesets:
    rtl:
        files:
            - src/some_file.sv

targets:
    default: &default
        filesets:
            - rtl

provider:
    name: git
    repo: <some_repo>
    version: v1.0.4-rc0

```
