### ISSUE TITLE
Missing fields for Spyglass options in CAPI2 format

### ISSUE THREAD

**Issue by amal-araweelo** [olofk/fusesoc#705]
Hello developer and users!

The Synopsis Spyglass backend (formerly Atrenta) is outdated. The supported fields are missing some newer options such as `set_goal_option`, ` current_goal`, `current_methodology`. I am currently using Spyglass v2023.12.+ as well as FuseSoC, which is where I ran into this problem. I found that the issue I had was actually due to the outdated backend of Spyglass. 

See Example snippet of current CAPI2 description file available for spyglass as a lint tool.

```
Example snippet of a CAPI2 description file

   spyglass:
     methodology: "GuideWare/latest/block/rtl_handoff"
     goals:
       - lint/lint_rtl
     spyglass_options:
       # prevent error SYNTH_5273 on generic RAM descriptions
       - handlememory yes
     rule_parameters:
       # Allow localparam to be used in case labels (e.g. in state machines)
       - handle_static_caselabels yes
```

I propose introducing `options` under `goals` as well as the ability to specify `current_methodogy` and ``current_goal`

I hope by opening this issue that it is something that can be looked into and perhaps update the Spyglass backend/FuseSoC.

Thank you in advance.
